from .academy_3_vs_1_with_keeper import Academy_3_vs_1_with_Keeper
from .academy_counterattack_easy import Academy_Counterattack_Easy
from .academy_counterattack_hard import Academy_Counterattack_Hard
